"""empty message

Revision ID: 7bbaec9d7771
Revises: 1669284bbab9
Create Date: 2024-04-02 12:40:54.042956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbaec9d7771'
down_revision = '1669284bbab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
